### PR TITLE
changed hostnames in toolbar.yml so toolbar works on local installs

### PR DESCRIPTION
**Pull request by SpiritLevel**

### CODE REVIEW

**Comment by camfindlay** [comment]
in 2 minds about this one. When we do work on the toolbar locally we need to point to local testing servers to carry out the work.

**Comment by SpiritLevel** [comment]
I thought as much, but decided to be a bit provocative! IMHO, if docs and userhelp are to be open source then local installs of their github repos should run as they do at SS. Perhaps some kind of dynamic configuration so that one version of toolbar.yml is used on SS test servers and the version in this PR ships with the Github repo ? Not knowing how SS test servers are organised, I don't know the best solution but this all seems like an unnecessary incompatibility and should be easy to fix :)

**Comment by camfindlay** [comment]
Yeah will have a think about an approach

**Comment by camfindlay** [comment]
FYI, if you just switch your env mode to "Live" in your _ss_environment.php it will use the toolbar from ss.org

**Comment by SpiritLevel** [comment]
Thanks Cam...I'll leave the change in my local toolbar.yml file as is for the time being while you consider an approach. I have all my dev work configured with a single _ss_environment.php and don't want to have to change it for this special case. I suppose I could put a special version of _ss_environment.php in the userhelp folder to override it, but this doesn't seem like how _ss_environment.php is meant to be used....correct me if I'm wrong!  In any case, we need a solution that doesn't put a barrier in the way of contributing.

**Comment by camfindlay** [comment]
this is totally how you can use ss env files :D

**Comment by SpiritLevel** [comment]
Closing : see changed hostname in toolbar.yml so toolbar works on local installs #95

**Pull request closed without merging**
