### PR TITLE
Cleaning up

### PR DESCRIPTION
**Pull request by SpiritLevel**
(i) returned cron task name to UpdateDocsCronTask since this should only ever contain the tasks for refreshing the source md files and for reindexing them. 
(ii) tidied up README.md

### CODE REVIEW

**Comment by camfindlay** [comment]
As long as you ensure docs.ss.org has the same naming I'll merge this.

**Comment by SpiritLevel** [comment]
I'll triple check :)

**Comment by camfindlay** [comment]
Have merged anyway but please do check and report back either way. We're looking to merge the platform branch into master today.

**Comment by SpiritLevel** [comment]
All is well with the names. I am happy to test the install and update instructions in README for both userhelp and doc once you are ready :) Just let me know.

**Pull request merged**
