### PR TITLE
DOCS Add required dependencies for ss3 user help

### PR DESCRIPTION
**Pull request by sachajudd**
Fixes https://github.com/silverstripe/userhelp.silverstripe.org/issues/52

### CODE REVIEW

**Comment by robbieaverill** [comment]
Does this need some other changes somewhere to link the SS3 userhelp docs to the right module versions?

**Comment by sachajudd** [comment]
@robbieaverill https://github.com/silverstripe/silverstripe-userhelp-content/pull/86

**Comment by robbieaverill** [comment]
Awesome :)

**Comment by robbieaverill** [comment]
Do you want me to merge the branches in userhelp content up for you?

**Comment by sachajudd** [comment]
Already done 🙂

**Pull request merged**
