### PR TITLE
new names for greater clarity; removed unnecessary file existence tests

### PR DESCRIPTION
**Pull request by SpiritLevel**
@camfindlay @mandrew : If you like the names I chose and other changes I made, I can do this also for docs. Just let me know :)

### CODE REVIEW

**Comment by camfindlay** [comment]
Will you make a PR to the docs site too with these same naming conventions? @SpiritLevel

**Comment by SpiritLevel** [comment]
@camfindlay I'll wait for feedback on my feedback for doing the same updates to doc.silverstripe.org :)

**Comment by camfindlay** [comment]
The versions will auto archive as we add more.

**Comment by SpiritLevel** [comment]
@camfindlay Re: versions....cool :)

Some of my comments seem to be disappearing! I raised a couple of questions here and they are gone....and it is now merged!

So, I think I'll open a clean PR and re-raise them, before heading over to docs to do the same thing.

**Pull request merged**
